# -*- mode: ruby -*-
# vi: set ft=ruby :
PORTS_LIST={
  "5432" => 5432, # postgres
}

Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "share/", "/home/vagrant/share"
  
  # port forwading
  PORTS_LIST.each do |guest, host|
  config.vm.network "forwarded_port", guest: "#{guest}", host: "#{host}"
  end
  
end
