# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "share/", "/home/vagrant/share"




end
